In [1]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [2]:
# 验证是否按预期工作
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-8.3819e-09, grad_fn=<MeanBackward0>)

## [**带参数的层**]

In [53]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.zeros(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [54]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.6363, -1.7154, -1.2989],
        [-0.0978, -0.5880,  0.7401],
        [-0.0565,  1.5028, -0.9941],
        [ 0.0057,  1.9439,  1.5594],
        [ 0.7767,  0.1972,  0.6559]], requires_grad=True)

In [55]:
linear(torch.rand(2, 5))

tensor([[0.5261, 0.2843, 0.2151],
        [0.8969, 0.5351, 0.7606]])

In [56]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[2.7081],
        [1.4159]])